plugins { id 'com.android.application' }
android {
    namespace 'com.sarf.qasioun.wallpaper'
    compileSdk 35
    defaultConfig {
        applicationId 'com.sarf.qasioun.wallpaper'
        minSdk 29
        targetSdk 35
        versionCode 3
        versionName '1.2.0-animated-flag-beta'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    lint { abortOnError true }
}
