plugins { id 'com.android.application' }
android {
    namespace 'com.sarf.qasioun.wallpaper'
    compileSdk 35
    defaultConfig {
        applicationId 'com.sarf.qasioun.wallpaper'
        minSdk 29
        targetSdk 35
        versionCode 5
        versionName '1.4.0-safe-folds-beta'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    lint { abortOnError true }
}
